// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package dbgen

import (
	"database/sql"
	"time"
)

type AiPerson struct {
	ID            int64
	UserName      int64
	Name          string
	ContextPrompt string
}

type AiPersonReply struct {
	ID           int64
	UserPromptID int64
	Status       string
	Message      string
	Timestamp    time.Time
}

type AiPersonReplyVoice struct {
	ID              int64
	AiPersonReplyID int64
	Status          string
	FileName        sql.NullString
}

type User struct {
	ID        int64
	Name      string
	Password  sql.NullString
	Status    string
	Challenge sql.NullString
}

type UserPrompt struct {
	ID         int64
	AiPersonID int64
	Timestamp  time.Time
}

type UserTextPrompt struct {
	ID           int64
	UserPromptID int64
	Message      string
}

type UserVoicePrompt struct {
	ID            int64
	UserPromptID  int64
	Status        string
	FileName      string
	Transcription sql.NullString
}

type VoiceModel struct {
	ID            int64
	VoiceSampleID int64
	Status        string
	FileName      sql.NullString
	Timestamp     time.Time
}

type VoiceSample struct {
	ID         int64
	AiPersonID int64
	FileName   sql.NullString
	Timestamp  time.Time
}
